### ISSUE TITLE
Front end and download server is getting closed automatically

### ISSUE THREAD

**Issue by tekkiram** [taroved/pol#1]
How to run the front end and download server in background? once i quit the terminal, both are getting terminated.

**Comment by taroved** [comment]
For development purposes I use tmux. In this case you just can detach from terminal with keys Ctrl+b + d and attach with command "tmux attach"

Or you can use bash control operator &
Example of usage: `python downloader.py &`

**Comment by tekkiram** [comment]
`python downloader.py &`
Even if i run in background,  once i close the terminal, it gets killed.  let me try tmux attach.  If it works, I am planning to add more fields, such as category, data, tags and other custom fields,  let me see how i can contribute to this script.

**Comment by taroved** [comment]
Yes, you can implement the new fields logic.
You can create github pull request with your changes. 
You can send your questions about PolitePol internals to my GitHub profile email address.

**Comment by taroved** [comment]
Any questions?
