### ISSUE TITLE
Restarted the server but..

### ISSUE THREAD

**Issue by Hasan0ff** [taroved/pol#11]
I restarted the server but can't make it work properly now.. The fronted doesn't work at all as it shows 502 bad gateway.. To keep the previous feeds up, I'm running downloader.py on console..

What can I do at the moment to fix everything?

**Comment by taroved** [comment]
You need to run frontend from directory ~/pol/frontend with command:
python manage.py runserver

Run in another console.

FYI: To make all work properly after server restart, you need to setup supervisord.
I can provide configuration for supervisord lately

**Comment by Hasan0ff** [comment]
alright

**Comment by Hasan0ff** [comment]
thanks for swift reply

**Comment by Hasan0ff** [comment]
both the frontend and the downloader are running with tmux and everything works fine now.. Thanks
