### ISSUE TITLE
How do I make this work?

### ISSUE THREAD

**Issue by SMylk** [taroved/pol#14]
Hi all,

I have a small google cloud vps where I want to run this, after install the website works, but creating feed always stops at:
[13/Mar/2018 17:39:46] "POST /setup_create_feed HTTP/1.0" 500 13972

**Comment by SMylk** [comment]
Nevermind, I got it, had to set:
[mysqld]
sql_mode=NO_ENGINE_SUBSTITUTION

**Comment by taroved** [comment]
Thank you for your investigation
