### ISSUE TITLE
Не работает с russian.rt.com

### ISSUE THREAD

**Issue by sojusnik** [taroved/pol#18]
На страницах

https://russian.rt.com/inotv/catalog/country/at
https://russian.rt.com/inotv/tag/%D0%90%D0%B2%D1%81%D1%82%D1%80%D0%B8%D1%8F

нельзя выбрать заголовок и описание.

**Comment by taroved** [comment]
Не все сайты позволяют просто выбрать заголовок.

Попробуйте поэкспериментировать с xpath.

Если вариант с xpath вас не устраивает, то при первой возможности я построю
их для вас

пт, 29 июня 2018 г. в 14:46, sojusnik <notifications@github.com>:

**Comment by taroved** [comment]
https://politepol.com/en/setup/18438
https://politepol.com/en/preview/18440

**Comment by sojusnik** [comment]
Спасибо!

А можно тоже описание статей добавить?

Если не тяжело, поделитесь пожалуйста ссылкой на "setup", а не на "preview", чтобы я её мог добавить в свои фиды на PolitePol.

Заранее благодарен!

**Comment by sojusnik** [comment]
Всё-таки сам разобрался :)

**Comment by sojusnik** [comment]
На тех страницах опять что-то поменялось :/

Не подскажите, как самому их заново можно настроить с помощью xpath? Может у вас есть ссылка на пособие или т.п.?

**Comment by taroved** [comment]
Все что могу предложить это руководство по xpath:
http://zvon.org/xxl/XPathTutorial/Output_rus/examples.html
