### ISSUE TITLE
Allowing for remote access

### ISSUE THREAD

**Issue by liamcs98** [taroved/pol#22]
Howdy,

Just wanted to make sure I'm not going insane. Is there a setting that prevents remote hosts from getting the page on port 8000?

If so where is there a config file somewhere I can edit to allow remote access?

**Comment by taroved** [comment]
No there isn’t. I use ubuntu farewall (ufw) to restrict access to the port

чт, 2 авг. 2018 г. в 19:23, William Smith <notifications@github.com>:

**Comment by liamcs98** [comment]
Thank you. I actually traced it to a different problem with a setting in Proxmox (where I am running the Ubuntu VM).
But for future people: 
sudo ufw allow 8000/tcp
sudo ufw allow 80/tcp

**Comment by SlavikCA** [comment]
In my case, I'm using Nginx not on the same host, as pol.
So, I had to change the way server is starting to this:
```
sudo python manage.py runserver 0.0.0.0:8000
```
