### ISSUE TITLE
Load Scripts option not displayed in self-hosted PolitePol

### ISSUE THREAD

**Issue by apolinario** [taroved/pol#27]
While I'm in https://politepol.com I can check the option "Load scripts" for a page.
However, when I self hosted the code avaliable here, this option is missing.

Am I doing something wrong?

**Comment by taroved** [comment]
Self histed PolitePol dosn’t have “Load scripts” functionality

вс, 31 марта 2019 г. в 22:22, apolinario <notifications@github.com>:
