### ISSUE TITLE
update frequency

### ISSUE THREAD

**Issue by Hasan0ff** [taroved/pol#5]
Hats up for awesome design and framework. May I know the update frequency the politepol uses to generate the feeds? Is it possible to manually change the frequency?

**Comment by taroved** [comment]
But if you will check data every second you can be banned by your target website. Be careful

**Comment by Hasan0ff** [comment]
So does it mean that the "feeds" are updated when I make a request(http request)?

**Comment by taroved** [comment]
Yes

**Comment by Hasan0ff** [comment]
Awesome. Thanks for quick reply.

**Comment by Hasan0ff** [comment]
I will be upfront with you, politepol can be compared head-to-head with high-end paid services. 

At the moment, its quite late so I'll be setting up a vps server tomorrow (already bought it) to test the politepol and hopefully, I'll be posting the performance of the politepol within the next month endless tests. Thanks for your hard work!

**Comment by taroved** [comment]
You are welcome!
