### ISSUE TITLE
how do I see list all my feeds?

### ISSUE THREAD

**Issue by sasagr** [taroved/pol#51]
I built it on ubuntu and all seems working fine. I created my first feed and it works (/feed/1). I created another one (/feed/2) and also ok but how do I see a list of them? How can I manage them (edit, delete, preview,..)?
I tried with localhost:8088/myfeeds but it does not work

**Comment by taroved** [comment]
Feeds are not editable

пн, 13 июля 2020 г. в 14:36, sasagr <notifications@github.com>:

**Comment by sasagr** [comment]
I see.. but maybe to be able to list them? how will I see the feed link I created for a specific website after some time?
also can I reset the db?

**Comment by taroved** [comment]
List is not implemented too. All feeds are located in frontend_feed mysql
table. I’m not sure If you can Reset database

пн, 13 июля 2020 г. в 15:17, sasagr <notifications@github.com>:
