### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Hasan0ff** [taroved/pol#7]
It's been almost a week that I've been using PolitePol... I have to note that the script is very efficient. I haven't done any reboots so this is the current memory status (there isn't even swap for just in case moments)

`root@vultr:~# free -h`
 `             total        used        free      shared  buff/cache   available`
`Mem:           996M        334M         61M         10M        599M        484M`
`Swap:            0B          0B          0B`
`root@vultr:~# `

more...

`Tasks:  85 total,   1 running,  84 sleeping,   0 stopped,   0 zombie`
`%Cpu0  :  0.3 us,  0.7 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st`

Overall after almost a week of non-stop usage on a low-end vps with 1GB ram just 334MB of ram is being used and 99% of the CPU is in idle state..

P.S: Each "feed" created by politepol is being pinged by another script on another server every 15 minutes to get the latest updates.

I believe that from the perspective of an end-user like me the results are superb at the moment. Hopefully, I'll be adding performance updates in a weekly manner for another 3 weeks.

**Comment by taroved** [comment]
Good numbers.
All memory leaks was fixed. So this numbers are not surprising.
If there are no differences in a week you can publish benchmarks monthly.
How many feeds do you actively use?

**Comment by Hasan0ff** [comment]
They are increasing as days pass so I'll add the number of feeds that are actively used on WEEK basis from now on. Good work mate! Hats up
