### ISSUE TITLE
Is it possible to add this functionality?

### ISSUE THREAD

**Issue by Hasan0ff** [taroved/pol#8]
Is it possible to add functionality so that politepol extracts all the links from the given webpage if the URL contains /news/ or /article/ or anything like that..

e.g target page http://www.example.com/ilovelife.php
in the target page there are 50 links which have /article/ in their URL..

**Comment by taroved** [comment]
You can edit xpath selectors in "Selectors editor" mode.
To extract links which contain /news/ or /article/ you can use in "Post xpath" something like this:
```//a[contains(@href, '/news/') or contains(@href, '/article/')]```

Let me know if you need more specific information.

**Comment by Hasan0ff** [comment]
thanks
