### ISSUE TITLE
Is it possible to make politepol...

### ISSUE THREAD

**Issue by Hasan0ff** [taroved/pol#9]
Is it possible to make politepol run javascript on pages that we try to create feed from?

**Comment by Hasan0ff** [comment]
for example, at feedity there is an option which says: Missing content? Load page scripts

**Comment by taroved** [comment]
Yes. It is possible and it's is should be implemented. But currently we don't have it

**Comment by Hasan0ff** [comment]
alright. thanks for the reply.
